# basic options
title: My Website Title
author: 20B2
email: bnod_468@hotmail.com
description: A wonderful website
twitter_username: 20B2
github_username: 20B2

#Build settings
markdown: kramdown
theme: jekyll-theme-midnight

