# basic options
title: Binod Marikhu
author: 20B2
email: bnod_468@hotmail.com
description: My GitHub pages
twitter_username: 20B2
github_username: 20B2

#Build settings
markdown: kramdown
theme: jekyll-theme-midnight

